### ISSUE TITLE
Basic Calculator

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/JavaScript#1]
Can you make a basic calculator code using javascript?

**Comment by imraghav20** [comment]
@akshitagupta15june Do we need to have a UI also for the calculator? Or just a simple calculator which takes 2 numbers and a operation as input, computes and gives the output?

**Comment by akshitagupta15june** [comment]
NO, UI part is not required as it is a beginner issue just a code having all basic operations will be perfect!
