### ISSUE TITLE
Strings-Remove Duplicates

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/JavaScript#13]
Take as input S, a string. Write a function that removes all consecutive duplicates. Print the value returned.
Input Format

String
Constraints

A string of length between 1 to 1000
Output Format

String
Sample Input

aabccba

Sample Output

abcba

Explanation

For the given example, "aabccba", Consecutive Occurrence of a is 2, b is 1, and c is 2.

After removing all of the consecutive occurences, the Final ans will be : - "abcba".

**Comment by akshitagupta15june** [comment]
add in strings repo of javascript

**Comment by 4Rebin** [comment]
Hey, I like to work on this issue.

**Comment by akshitagupta15june** [comment]
PROCESS OF CONTRIBUTION IN THIS REPOSITORY

FORK THIS REPOSITORY
ADD YOUR CODE IN RESPECTIVE FOLDER
CREATE A PULL REQUEST
AFTER A SIMPLE CHECK I WILL MERGE THE PR

HAPPY CODING AND CONTRIBUTING!!!!

**Comment by resparx** [comment]
The code is already present , could you please close this issue 😃

**Comment by akshitagupta15june** [comment]
CLOSED

**Comment by resparx** [comment]
🤝 @akshitagupta15june
