### ISSUE TITLE
git clone creates empty directory

### ISSUE THREAD

**Issue by nilaylilawala** [akshitagit/JavaScript#150]
Hey Akshita,

I recently forked JavaScript repo and when I cloned, the directory was empty. I examined and found that add-license-1 branch contains the code while master is empty. By default we are directed to the master branch.

Kindly check the issue and please resolve asap.

**Comment by gsvh** [comment]
Hi @nilaylilawala, I have just cloned the repo and did not have the same issue. I forked it and cloned it from there. Hope this helps 🙌

**Comment by nilaylilawala** [comment]
Oh. That must be a problem on my side. Thank you for informing.
