### ISSUE TITLE
Create Selection Sort

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/JavaScript#25]

**Comment by VolatianaYuliana** [comment]
Hey @akshitagupta15june! I would like to work on this one.

**Comment by akshitagupta15june** [comment]
Asssigned

PROCESS OF CONTRIBUTION IN THIS REPOSITORY

FORK THIS REPOSITORY
ADD YOUR CODE IN RESPECTIVE FOLDER
CREATE A PULL REQUEST
AFTER A SIMPLE CHECK I WILL MERGE THE PR

HAPPY CODING AND CONTRIBUTING!!!!

**Comment by harshvardhan614** [comment]
Hi @akshitagupta15june mam, can I work on this issue if it is still open?

**Comment by akshitagupta15june** [comment]
its completed
