### ISSUE TITLE
Hour glass Pattern

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/JavaScript#4]
Take N as input. For a value of N=5, we wish to draw the following pattern :

                      5 4 3 2 1 0 1 2 3 4 5
                        4 3 2 1 0 1 2 3 4 
                          3 2 1 0 1 2 3 
                            2 1 0 1 2 
                              1 0 1 
                                0 
                              1 0 1 
                            2 1 0 1 2 
                          3 2 1 0 1 2 3 
                        4 3 2 1 0 1 2 3 4 
                      5 4 3 2 1 0 1 2 3 4 5

Input Format

Take N as input.
Constraints

N <= 20
Output Format

Pattern should be printed with a space between every two values.
Sample Input

5

**Comment by akshitagupta15june** [comment]
Add in patterns repo of javascript.

**Comment by pranavmittal611** [comment]
Pull request #8
