### ISSUE TITLE
CREATE A HOLLOW RHOMBUS PATTERN

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/JavaScript#42]
Take N (number of rows), print the following pattern (for N = 5).

     * * * * *
     * *   * *
     *       *
     * *   * *
     * * * * *

Input Format

Constraints

0 < N < 10 (where N is an odd number)

**Comment by akshitagupta15june** [comment]
ADD IN PATTERNS FOLDER

**Comment by ngdangtu-vn** [comment]
Hello, I would like to challenge myself this issue. But before getting start, I would like to confirm is that the diamon hollow shape? (like diamon shape in a card)

**Comment by akshitagupta15june** [comment]
ofcourse, i am assigning it to u

**Comment by ngdangtu-vn** [comment]
... After I finished, I suddenly realize that.. do you guys accept... C++? Because I'd seen it somewhere but now I couldn't see it anymore...

Tell me if you need me to remake it to Js version. (I'm good with Js anyway)

**Comment by ngdangtu-vn** [comment]
@akshitagupta15june Hello, I've completed your issue for awhile. Could you mind to checkout my PR please? If it is good enough, would you please mark it as legal for Hacktoberfest?
