### ISSUE TITLE
MATRIX SEARCH

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagit/JavaScript#46]
STAR THIS REPO!

Given an n x m matrix, where every row and column is sorted in increasing order, and a number x . Find if element x is present in the matrix or not.

Input Format

First line consists of two space separated integers N and M, denoting the number of element in a row and column respectively. Second line of each test case consists of N*M space separated integers denoting the elements in the matrix in row major order. Third line of each test case contains a single integer x, the element to be searched.
Constraints

1 <= N,M <= 30 0 <= A[i] <= 100000

Output Format

Print 1 if the element is present in the matrix, else 0.

Sample Input

3 3
3 30 38
44 52 54
57 60 69

62

Sample Output

0

**Comment by akshitagupta15june** [comment]
ADD IN SEARCH REPO

**Comment by Kevnien** [comment]
@akshitagupta15june I'll take this one.

**Comment by akshitagupta15june** [comment]
Ok
